import type { Metadata } from "next";
import { SiteFooter } from "@/components/site/SiteFooter";
import { SiteHeader } from "@/components/site/SiteHeader";
import { SITE_NAME } from "@/lib/brand";

export const metadata: Metadata = {
  title: `Privacy & Copyright — ${SITE_NAME}`,
  description: "How your data, uploads, and system-generated content are handled.",
};

export default function PrivacyPage() {
  return (
    <div className="flex min-h-full flex-col">
      <SiteHeader />
      <main className="mx-auto w-full max-w-2xl flex-1 px-6 py-12">
        <h1 className="font-serif text-3xl font-semibold text-[var(--color-text)]">Privacy &amp; copyright</h1>
        <p className="mt-2 text-sm text-[var(--color-text-muted)]">
          Plain-language summary of how the service handles your data. This describes intended behavior of the
          product as built; it is not legal advice.
        </p>

        <div className="mt-8 flex flex-col gap-6 text-[var(--color-text)]">
          <Section title="What we store">
            Your account (name, email, a hashed password), the texts you upload and the text extracted from them,
            and everything you create: highlights, notes, bookmarks, reading status, understanding ratings, and any
            corrections you make to automated annotations. Preferences such as your expertise level are stored to
            personalize the roadmap.
          </Section>

          <Section title="Your data is isolated to you">
            Every piece of your content is scoped to your account and never visible to other users. Requests for a
            resource you don&rsquo;t own return &ldquo;not found&rdquo; rather than revealing it exists.
          </Section>

          <Section title="Copyright — you bring your own texts">
            The service never bypasses paywalls or sources copyrighted material on your behalf. For works it
            can&rsquo;t obtain, it stores a proper citation and a pointer toward legitimate acquisition, and lets you
            upload your own legally obtained copy. Roadmap and analysis still work for works not directly inspected,
            marking them accordingly.
          </Section>

          <Section title="Automated classification">
            Bibliographic facts come only from real lookups (Crossref, OpenAlex, Open Library), never generated by a
            model. When a classification model is used to classify how references relate to a text, calls go to the
            provider&rsquo;s API tier under its data-use terms. Your uploaded content is never used to train models
            without your explicit, separate opt-in — the default is opt-out.
          </Section>

          <Section title="Deletion &amp; export">
            Deleting your account removes your uploaded files, extracted text, annotations, and derived data — not
            just the account record. You can export your notes, roadmap, and bibliography.
          </Section>

          <Section title="A research aid, not settled scholarship">
            Every system-generated claim carries a confidence and its provenance, explaining the basis for the
            inference rather than presenting it as settled fact. Verify against the primary text before relying on
            anything; you can correct, dispute, or hide any automated annotation.
          </Section>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-serif text-lg font-semibold text-[var(--color-text)]">{title}</h2>
      <p className="mt-1 leading-relaxed text-[var(--color-text-muted)]">{children}</p>
    </section>
  );
}
